export const cityList = {
    default: '城市',
    Taipei: '臺北市',
    NewTaipei: '新北市',
    Taoyuan: '桃園市',
    Taichung: '臺中市',
    Tainan: '臺南市',
    Kaohsiung: '高雄市',
    Keelung: '基隆市',
    Hsinchu: '新竹市',
    HsinchuCounty: '新竹縣',
    MiaoliCounty: '苗栗縣',
    ChanghuaCounty: '彰化縣',
    NantouCounty: '南投縣',
    YunlinCounty: '雲林縣',
    ChiayiCounty: '嘉義縣',
    Chiayi: '嘉義市',
    PingtungCounty: '屏東縣',
    YilanCounty: '宜蘭縣',
    HualienCounty: '花蓮縣',
    TaitungCounty: '臺東縣',
    KinmenCounty: '金門縣',
    PenghuCounty: '澎湖縣',
    LienchiangCounty: '連江縣',
};

export const classList = {
    default: '類型',
    文化類: '文化類',
    觀光工廠類: '觀光工廠類',
    自然風景類: '自然風景類',
    生態類: '生態類',
    國家風景區類: '國家風景區類',
    遊憩類: '遊憩類',
    其他: '其他',
    廟宇類: '廟宇類',
    體育健身類: '體育健身類',
    林場類: '林場類',
    休閒農業類: '休閒農業類',
    溫泉類: '溫泉類',
    古蹟類: '古蹟類',
    特產類: '小吃/特產類',
    藝術類: '藝術類',
    森林遊樂區類: '森林遊樂區類',
    國家公園類: '國家公園類',
    都會公園類: '都會公園類',
};
